"""IAB Content Taxonomy 3.0 - Tier 1 and Tier 2 categories."""

IAB_TAXONOMY = {
    "1": {
        "name": "Arts & Entertainment",
        "subcategories": {
            "1-1": "Animation",
            "1-2": "Arts & Crafts",
            "1-3": "Celebrity Fan/Gossip",
            "1-4": "Humor",
            "1-5": "Opera",
        },
    },
    "2": {
        "name": "Automotive",
        "subcategories": {
            "2-1": "Auto Parts",
            "2-2": "Auto Repair",
            "2-3": "Buying/Selling Cars",
            "2-4": "Car Culture",
            "2-5": "Certified Pre-Owned",
            "2-6": "Convertible",
            "2-7": "Coupe",
            "2-8": "Crossover",
            "2-9": "Diesel",
            "2-10": "Electric Vehicle",
            "2-11": "Hatchback",
            "2-12": "Hybrid",
            "2-13": "Luxury",
            "2-14": "MiniVan/Van",
            "2-15": "Off-Road Vehicles",
            "2-16": "Performance Vehicles",
            "2-17": "Pickup",
            "2-18": "Road-Side Assistance",
            "2-19": "Sedan",
            "2-20": "Trucks & Accessories",
            "2-21": "Vintage Cars",
            "2-22": "Wagon",
        },
    },
    "3": {
        "name": "Business & Finance",
        "subcategories": {
            "3-1": "Business News",
            "3-2": "Company News",
            "3-3": "Economy",
            "3-4": "Entrepreneurship",
            "3-5": "Financial Regulation",
            "3-6": "Fiscal Policy",
            "3-7": "Investment",
            "3-8": "Marketing & Advertising",
            "3-9": "Mergers & Acquisitions",
            "3-10": "Personal Finance",
            "3-11": "Real Estate",
            "3-12": "Startups",
        },
    },
    "4": {
        "name": "Careers",
        "subcategories": {
            "4-1": "Career Advice",
            "4-2": "Career Planning",
            "4-3": "Job Search",
            "4-4": "Job Fairs",
            "4-5": "Remote Working",
            "4-6": "Resume Writing",
        },
    },
    "5": {
        "name": "Education",
        "subcategories": {
            "5-1": "Adult Education",
            "5-2": "Art History",
            "5-3": "College Education",
            "5-4": "College Life",
            "5-5": "Distance Learning",
            "5-6": "English as a Second Language",
            "5-7": "Graduate School",
            "5-8": "Homeschooling",
            "5-9": "Homework/Study Tips",
            "5-10": "K-6 Educators",
            "5-11": "Language Learning",
            "5-12": "Private School",
            "5-13": "Special Education",
            "5-14": "Studying Business",
        },
    },
    "6": {
        "name": "Events & Attractions",
        "subcategories": {
            "6-1": "Amusement & Theme Parks",
            "6-2": "Bars, Clubs & Nightlife",
            "6-3": "Comedy",
            "6-4": "Concerts",
            "6-5": "Dance & Electronic Music",
            "6-6": "Film Festivals",
            "6-7": "Food & Drink Events",
            "6-8": "Fundraising",
            "6-9": "Music Festivals",
            "6-10": "Museums",
            "6-11": "Outdoor Activities",
            "6-12": "Performing Arts",
            "6-13": "Sporting Events",
            "6-14": "Tour Events",
        },
    },
    "7": {
        "name": "Family & Relationships",
        "subcategories": {
            "7-1": "Dating",
            "7-2": "Divorce Support",
            "7-3": "Eldercare",
            "7-4": "Marriage",
            "7-5": "Parenting",
            "7-6": "Special Needs Kids",
        },
    },
    "8": {
        "name": "Fine Art",
        "subcategories": {
            "8-1": "Art History",
            "8-2": "Body Art/Tattoos",
            "8-3": "Dance",
            "8-4": "Design",
            "8-5": "Digital Arts",
            "8-6": "Drawing/Sketching",
            "8-7": "Painting",
            "8-8": "Photography",
            "8-9": "Sculpture",
        },
    },
    "9": {
        "name": "Food & Drink",
        "subcategories": {
            "9-1": "Alcoholic Beverages",
            "9-2": "Barbecues & Grilling",
            "9-3": "Cocktails/Beer",
            "9-4": "Coffee/Tea",
            "9-5": "Cuisine-Specific",
            "9-6": "Desserts & Baking",
            "9-7": "Dining Out",
            "9-8": "Food Allergies",
            "9-9": "Food Movements",
            "9-10": "Healthy Cooking and Eating",
            "9-11": "Non-Alcoholic Beverages",
            "9-12": "Recipes",
            "9-13": "Vegan",
            "9-14": "Vegetarian",
            "9-15": "Wine",
        },
    },
    "10": {
        "name": "Healthy Living",
        "subcategories": {
            "10-1": "Alternative Medicine",
            "10-2": "Children's Health",
            "10-3": "Fitness & Exercise",
            "10-4": "Meditation/Yoga",
            "10-5": "Men's Health",
            "10-6": "Nutrition",
            "10-7": "Senior Health",
            "10-8": "Weight Loss",
            "10-9": "Women's Health",
        },
    },
    "11": {
        "name": "Hobbies & Interests",
        "subcategories": {
            "11-1": "Art/Technology",
            "11-2": "Beekeeping",
            "11-3": "Birdwatching",
            "11-4": "Board Games/Puzzles",
            "11-5": "Candle & Soap Making",
            "11-6": "Card Games",
            "11-7": "Chess",
            "11-8": "Cigars",
            "11-9": "Collecting",
            "11-10": "Comic Books",
            "11-11": "Drawing/Sketching",
            "11-12": "Free Software",
            "11-13": "Genealogy",
            "11-14": "Getting Published",
            "11-15": "Guitar",
            "11-16": "Home Recording",
            "11-17": "Inventors and Patents",
            "11-18": "Jewelry Making",
            "11-19": "Magic & Illusion",
            "11-20": "Needlework",
            "11-21": "Painting",
            "11-22": "Photography",
            "11-23": "Radio",
            "11-24": "Roleplaying Games",
            "11-25": "Sci-Fi & Fantasy",
            "11-26": "Scrapbooking",
            "11-27": "Screenwriting",
            "11-28": "Stamps & Coins",
            "11-29": "Video & Computer Games",
            "11-30": "Woodworking",
        },
    },
    "12": {
        "name": "Home & Garden",
        "subcategories": {
            "12-1": "Appliances",
            "12-2": "Entertaining",
            "12-3": "Environmental Safety",
            "12-4": "Gardening",
            "12-5": "Home Repair",
            "12-6": "Home Theater",
            "12-7": "Interior Decorating",
            "12-8": "Landscaping",
            "12-9": "Remodeling & Construction",
        },
    },
    "13": {
        "name": "Medical Health",
        "subcategories": {
            "13-1": "Allergies",
            "13-2": "Alternative Medicine",
            "13-3": "Arthritis",
            "13-4": "Assisted Living",
            "13-5": "Autism Spectrum Disorder",
            "13-6": "Cancer",
            "13-7": "Cholesterol",
            "13-8": "Chronic Pain",
            "13-9": "Cold & Flu",
            "13-10": "Deafness",
            "13-11": "Dental Health",
            "13-12": "Depression",
            "13-13": "Diabetes",
            "13-14": "Epilepsy",
            "13-15": "GERD/Acid Reflux",
            "13-16": "Headaches/Migraines",
            "13-17": "Heart Disease",
            "13-18": "Herbs for Health",
            "13-19": "Holistic Healing",
            "13-20": "IBS/Crohn's Disease",
            "13-21": "Men's Health",
            "13-22": "Mental Health",
            "13-23": "Nutrition",
            "13-24": "Orthopedics",
            "13-25": "Panic/Anxiety Disorders",
            "13-26": "Pediatrics",
            "13-27": "Physical Therapy",
            "13-28": "Psychology/Psychiatry",
            "13-29": "Senior Health",
            "13-30": "Sexuality",
            "13-31": "Sleep Disorders",
            "13-32": "Smoking Cessation",
            "13-33": "Substance Abuse",
            "13-34": "Thyroid Disease",
            "13-35": "Weight Loss",
            "13-36": "Women's Health",
        },
    },
    "14": {
        "name": "Movies",
        "subcategories": {
            "14-1": "Action & Adventure Films",
            "14-2": "Animation Films",
            "14-3": "Comedy Films",
            "14-4": "Documentary Films",
            "14-5": "Drama Films",
            "14-6": "Foreign Films",
            "14-7": "Horror Films",
            "14-8": "Independent Films",
            "14-9": "Movie Reviews",
            "14-10": "Musical Films",
            "14-11": "Science Fiction Films",
        },
    },
    "15": {
        "name": "Music & Audio",
        "subcategories": {
            "15-1": "Adult Contemporary Music",
            "15-2": "Bluegrass Music",
            "15-3": "Blues Music",
            "15-4": "Classical Music",
            "15-5": "Country Music",
            "15-6": "Electronic Music",
            "15-7": "Folk Music",
            "15-8": "Gospel Music",
            "15-9": "Hip Hop Music",
            "15-10": "Jazz Music",
            "15-11": "Latin Music",
            "15-12": "Metal Music",
            "15-13": "New Age Music",
            "15-14": "Opera Music",
            "15-15": "Pop Music",
            "15-16": "R&B/Soul",
            "15-17": "Rap Music",
            "15-18": "Reggae",
            "15-19": "Rock Music",
            "15-20": "Soundtracks",
            "15-21": "World Music",
        },
    },
    "16": {
        "name": "News & Politics",
        "subcategories": {
            "16-1": "Crime",
            "16-2": "Death & Tragedy",
            "16-3": "Disasters",
            "16-4": "Economic News",
            "16-5": "Education News",
            "16-6": "Health News",
            "16-7": "International News",
            "16-8": "Law",
            "16-9": "Local News",
            "16-10": "National News",
            "16-11": "Politics",
            "16-12": "Science News",
            "16-13": "Sports News",
            "16-14": "Technology News",
            "16-15": "War & Conflict",
            "16-16": "Weather",
        },
    },
    "17": {
        "name": "Personal Finance",
        "subcategories": {
            "17-1": "Beginning Investing",
            "17-2": "Credit/Debt & Loans",
            "17-3": "Financial News",
            "17-4": "Financial Planning",
            "17-5": "Hedge Funds",
            "17-6": "Insurance",
            "17-7": "Investing",
            "17-8": "Mutual Funds",
            "17-9": "Options",
            "17-10": "Retirement Planning",
            "17-11": "Stocks",
            "17-12": "Tax Planning",
        },
    },
    "18": {
        "name": "Pets",
        "subcategories": {
            "18-1": "Aquariums",
            "18-2": "Birds",
            "18-3": "Cats",
            "18-4": "Dogs",
            "18-5": "Large Animals",
            "18-6": "Reptiles",
            "18-7": "Veterinary Medicine",
        },
    },
    "19": {
        "name": "Pop Culture",
        "subcategories": {
            "19-1": "Celebrity News",
            "19-2": "Entertainment News",
            "19-3": "Gossip",
            "19-4": "Viral Content",
        },
    },
    "20": {
        "name": "Real Estate",
        "subcategories": {
            "20-1": "Apartments",
            "20-2": "Architects",
            "20-3": "Buying/Selling Homes",
            "20-4": "Foreclosures",
            "20-5": "Green Solutions",
            "20-6": "Home Inspections",
            "20-7": "Moving",
            "20-8": "Renting/Leasing",
            "20-9": "Vacation Properties",
        },
    },
    "21": {
        "name": "Religion & Spirituality",
        "subcategories": {
            "21-1": "Alternative Religions",
            "21-2": "Atheism/Agnosticism",
            "21-3": "Buddhism",
            "21-4": "Catholicism",
            "21-5": "Christianity",
            "21-6": "Hinduism",
            "21-7": "Islam",
            "21-8": "Judaism",
            "21-9": "Latter-Day Saints",
            "21-10": "Pagan/Wiccan",
        },
    },
    "22": {
        "name": "Science",
        "subcategories": {
            "22-1": "Astrology",
            "22-2": "Biology",
            "22-3": "Chemistry",
            "22-4": "Environment",
            "22-5": "Genetics",
            "22-6": "Geography",
            "22-7": "Geology",
            "22-8": "Physics",
            "22-9": "Space/Astronomy",
            "22-10": "Weather",
        },
    },
    "23": {
        "name": "Shopping",
        "subcategories": {
            "23-1": "Couponing",
            "23-2": "Comparison Shopping",
            "23-3": "Contests & Freebies",
            "23-4": "Luxury Shopping",
            "23-5": "Online Shopping",
            "23-6": "Price Guides & Comparisons",
        },
    },
    "24": {
        "name": "Sports",
        "subcategories": {
            "24-1": "American Football",
            "24-2": "Auto Racing",
            "24-3": "Baseball",
            "24-4": "Basketball",
            "24-5": "Boxing",
            "24-6": "Canoeing/Kayaking",
            "24-7": "Cheerleading",
            "24-8": "Climbing",
            "24-9": "Cricket",
            "24-10": "Cycling",
            "24-11": "Darts",
            "24-12": "Disabled Sports",
            "24-13": "Extreme Sports",
            "24-14": "Fantasy Sports",
            "24-15": "Field Hockey",
            "24-16": "Figure Skating",
            "24-17": "Fly Fishing",
            "24-18": "Football/Soccer",
            "24-19": "Freshwater Fishing",
            "24-20": "Golf",
            "24-21": "Horse Racing",
            "24-22": "Hunting/Shooting",
            "24-23": "Inline Skating",
            "24-24": "Martial Arts",
            "24-25": "Motorcycle Racing",
            "24-26": "NASCAR Racing",
            "24-27": "Olympics",
            "24-28": "Rowing/Crew",
            "24-29": "Sailing",
            "24-30": "Skateboarding",
            "24-31": "Skiing",
            "24-32": "Snowboarding",
            "24-33": "Surfing",
            "24-34": "Swimming",
            "24-35": "Tennis",
            "24-36": "Track & Field/Running",
            "24-37": "Volleyball",
            "24-38": "Wrestling",
        },
    },
    "25": {
        "name": "Style & Fashion",
        "subcategories": {
            "25-1": "Beauty",
            "25-2": "Body Art",
            "25-3": "Clothing",
            "25-4": "Fashion",
            "25-5": "Jewelry",
            "25-6": "Men's Fashion",
            "25-7": "Personal Care",
            "25-8": "Street Style",
            "25-9": "Women's Fashion",
        },
    },
    "26": {
        "name": "Technology & Computing",
        "subcategories": {
            "26-1": "Artificial Intelligence",
            "26-2": "Augmented Reality",
            "26-3": "Blockchain & Cryptocurrency",
            "26-4": "Cameras & Photography",
            "26-5": "Cloud Computing",
            "26-6": "Computer Hardware",
            "26-7": "Computer Networking",
            "26-8": "Consumer Electronics",
            "26-9": "Cybersecurity",
            "26-10": "Data Science",
            "26-11": "Databases",
            "26-12": "Gadgets & Electronics",
            "26-13": "Internet of Things",
            "26-14": "Internet Technology",
            "26-15": "Machine Learning",
            "26-16": "Mobile Apps",
            "26-17": "Mobile Phones",
            "26-18": "Open Source Software",
            "26-19": "Operating Systems",
            "26-20": "Programming",
            "26-21": "Robotics",
            "26-22": "Semiconductors",
            "26-23": "Social Media",
            "26-24": "Software",
            "26-25": "Virtual Reality",
            "26-26": "Wearable Technology",
            "26-27": "Web Design & Development",
        },
    },
    "27": {
        "name": "Television & Streaming",
        "subcategories": {
            "27-1": "Animation TV",
            "27-2": "Comedy TV",
            "27-3": "Documentary TV",
            "27-4": "Drama TV",
            "27-5": "Reality TV",
            "27-6": "Sci-Fi TV",
            "27-7": "Sports TV",
            "27-8": "Streaming Services",
            "27-9": "Talk Shows",
        },
    },
    "28": {
        "name": "Travel",
        "subcategories": {
            "28-1": "Adventure Travel",
            "28-2": "Africa",
            "28-3": "Air Travel",
            "28-4": "Asia",
            "28-5": "Australia & New Zealand",
            "28-6": "Budget Travel",
            "28-7": "Business Travel",
            "28-8": "Canada",
            "28-9": "Caribbean",
            "28-10": "Cruises",
            "28-11": "Europe",
            "28-12": "Family Vacations",
            "28-13": "Hotels",
            "28-14": "Latin America",
            "28-15": "Luxury Travel",
            "28-16": "Middle East",
            "28-17": "National Parks",
            "28-18": "Road Trips",
            "28-19": "United States",
        },
    },
    "29": {
        "name": "Video Gaming",
        "subcategories": {
            "29-1": "Action & Adventure Games",
            "29-2": "Casual Games",
            "29-3": "Classic Video Games",
            "29-4": "Console Games",
            "29-5": "Esports",
            "29-6": "Fighting Games",
            "29-7": "Gaming Culture",
            "29-8": "Mobile Games",
            "29-9": "MMO Games",
            "29-10": "PC Games",
            "29-11": "Puzzle Games",
            "29-12": "Racing Games",
            "29-13": "Role-Playing Games",
            "29-14": "Simulation Games",
            "29-15": "Sports Video Games",
        },
    },
    "30": {
        "name": "Crime, Law & Justice",
        "subcategories": {
            "30-1": "Crime",
            "30-2": "Legal Issues",
            "30-3": "Law Enforcement",
            "30-4": "Prisons",
            "30-5": "True Crime",
        },
    },
}


def get_taxonomy_context() -> str:
    """Return a formatted string of the taxonomy for use in prompts."""
    lines = []
    for tier1_id, tier1_data in IAB_TAXONOMY.items():
        lines.append(f"[{tier1_id}] {tier1_data['name']}")
        for tier2_id, tier2_name in tier1_data["subcategories"].items():
            lines.append(f"  [{tier2_id}] {tier2_name}")
    return "\n".join(lines)


def get_tier1_name(tier1_id: str) -> str:
    entry = IAB_TAXONOMY.get(tier1_id)
    return entry["name"] if entry else "Unknown"


def get_tier2_name(tier2_id: str) -> str:
    if not tier2_id:
        return None
    tier1_id = tier2_id.split("-")[0]
    entry = IAB_TAXONOMY.get(tier1_id)
    if entry:
        return entry["subcategories"].get(tier2_id)
    return None
